apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: node-app
              namespaces:
              - frontend
              topologyKey: kubernetes.io/hostname
      containers:
      - name: node-app
        image: us-central1-docker.pkg.dev/amin-final/project-repo/node-app:latest
        ports:
        - name: http
          containerPort: 27017
        env:
        - name: MONGODB_HOSTNAME
          value: mongodb-0.mongodb-headless.backend
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: test
        - name: MONGODB_DATABASE
          value: inventory  
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: node-app-secrets
              key: DBpass
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
