apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: frontend
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: LoadBalancer